### ISSUE TITLE
fileSize field in JSON response not in IndexRes

### ISSUE THREAD

**Issue by AndyHaskell** [algolia/algoliasearch-client-go#105]
I noticed using a cURL call to the `/1/indexes` route that there is a field in the JSON response called "fileSize", which contains the index size shown when looking at an index in the dashboard. However, there is no corresponding field in the `IndexRes` struct in v2 of the Go client. Could this be added?

**Comment by aseure** [comment]
Hello @AndyHaskell and thank you for reporting the issue.

The `fileSize` field was indeed not exposed and it is not intended. I've checked the endpoint and discovered that the `numberOfPendingTask` field was also missing. Those omissions were due to the fact that we forget to add them to our REST API documentation on which we rely for the implementation of our API clients.

I've merged #106 on `master` to expose those two missing fields. I've also updated [our REST API documentation](https://www.algolia.com/doc/rest-api/search#list-indexes) and pinged all our API client maintainers to tell them the documentation was updated so that they could update the our API clients accordingly.

Sorry for the inconvenience it may have caused and thank you again for reporting the issue.
