### ISSUE TITLE
SetSettings gets wrong parameter (algoliasearch.Map)

### ISSUE THREAD

**Issue by sharpner** [algolia/algoliasearch-client-go#108]
hey!

The documentation specifies that index.SetSettings gets a Settings object, but the actual method requires a Map object. Also the GetSettings returns a Settings object.

This is kinda confusing for beginners. Is it a documentation bug, or a code bug? 

Thanks in advance.

**Comment by aseure** [comment]
Hello @sharpner.

It was indeed a mistake. I fixed the documentation accordingly (see #109).

To be clear, the `GetSettings` returns a `Settings` object so that it's easier to understand and browse all the settings of an index. However, we decided to use a `Map` for the `SetSettings` in order to let the final user set only the needed settings without having to worry about all the other ones and their default values.

Could you tell me if the documentation/README seems better to you now? If not, don't hesitate to tell me what can be improved. :)

**Comment by sharpner** [comment]
thanks for the fast response - it's working now :)

While you are at fixing typos: there is also `algoliasearchearch` instead of `algoliasearch` :P

but my problem is fixed!

**Comment by aseure** [comment]
You're welcome and thank you again for the other typo you mentioned (fixed by #110).

**Comment by cochran-at-niche** [comment]
This design (where GetSettings returns a struct, but SetSettings takes a map) makes it extremely difficult to copy the settings from an existing index to a temporary index - a pattern that is suggested many times throughout your documentation. For example:

- https://www.algolia.com/doc/faq/index-configuration/how-can-i-update-all-the-objects-of-my-index
- https://github.com/algolia/algoliasearch-client-go#move-index---moveindex).

 Please reconsider this design, as there is currently no easy way to go from the Settings struct to a Map (JSON Marshaling the struct, and then Unmarshaling it into a Map, results in incorrectly typed fields. I get the error message: `disableTypoToleranceOnWords should be of type []string`).

I don't think your reasoning ("...in order to let the final user set only the needed settings without having to worry about all the other ones and their default values") actually makes much sense. You may want to look into the "omitempty" JSON struct field tag: https://golang.org/pkg/encoding/json/

**Comment by aseure** [comment]
Hello @cochran-at-niche. Thank you for pointing out the issue.

I agree with you that using `GetSettings`/`SetSettings` to copy index settings is not easy with the Go client in the end. However, we cannot use the `Settings struct` for the `SetSettings` because it would mean that every single parameter needs to be set by the user explicitly. On the other hand, with the `Map` approach, only the needed parameters are set and the other ones remain untouched. Also, `omitempty` won't help here as it means that `false`, `0` and `nil` values won't be in the JSON, even if the user is explicitly setting them.

An other solution we considered is to use `Map` everywhere and let the user do the extra casting each time. I'm not convinced by this solution on a usage point of view and it would introduce a breaking change for all our users.

As an in between solution, because you're definitely right saying that right now it's difficult to use, we can instead add a function that produce the `Map` out of a `Settings struct`. That way, the workflow would become `GetSettings` -> `ConvertSettingsToMap` -> `SetSettings` (leaving the `GetSettings`/`SetSettings` untouched). This solution doesn't introduce any breaking change.

What do you think? :)

**Comment by cochran-at-niche** [comment]
Yeah, that sounds reasonable to me!

**Comment by aseure** [comment]
@cochran-at-niche Thank you again for your feedback.

I've added a `ToMap` method to the `Settings struct` in order to let our users copy the settings more easily by doing `SetSettings(settings.ToMap())`. Check the `TestSettingsToMap` test as an example: https://github.com/algolia/algoliasearch-client-go/pull/137/commits/faef1a4f56cba027961f3c64a534f9ef082830d2

Kind regards. ;)

**Comment by cochran-at-niche** [comment]
Thanks! I really appreciate it!

**Comment by aseure** [comment]
@cochran-at-niche You're very welcome.
