### ISSUE TITLE
Bug: Unable to use SaveObjects with int64 type

### ISSUE THREAD

**Issue by townsymush** [algolia/algoliasearch-client-go#612]
- Algolia Client Version: 3.8.0
- Language Version: 1.14.2

### Description
When uploading various objects to Algolia using the SDK, We have found that we get the following error: `constant 9223372036854775808 overflows int`

### Steps To Reproduce
Sample code to replicate bug

```golang
package main

import (
	"github.com/algolia/algoliasearch-client-go/v3/algolia/opt"
	"github.com/algolia/algoliasearch-client-go/v3/algolia/search"
	"log"
)

type testInt struct {
	bigInt int64
}

func main() {
	client := search.NewClient("id", "secret")
	index := client.InitIndex("index")


	// This Passes
	ti := testInt{bigInt: 12345}
	_, err := index.SaveObjects(ti, opt.AutoGenerateObjectIDIfNotExist(true))
	if err != nil {
		log.Fatal(err)
	}

	// This Fails
	ti = testInt{bigInt: 9223372036854775808}
	_, err = index.SaveObjects(ti, opt.AutoGenerateObjectIDIfNotExist(true))
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by aseure** [comment]
Hello @townsymush and thank you for contacting us.

What you are trying to do is not possible with plain integers but luckily, there are some solutions.

First of all, what you are trying to do will just not compile in Go because you are trying to store the number `2^63` within an `int64` which only represents values within the range `[-2^63;2^63-1]`. In Go, you have two alternatives for that. You can either use an `uint64` which is able to store values within the range `[0; 2^64-1]`. If you need to manipulate values outside of this range, you can still fallback to the `math/big` arbitrary-precision library from the Go standard library, such as:

```go
i := big.NewInt(9223372036854775807)
i = i.Add(i, big.NewInt(1))
```

Then, there's a second problem, at the JSON level: JSON is only able to represent integer values up to `2^53`. So, you cannot send numbers higher than that to a JSON REST API such as Algolia. What you can do instead, is to convert your arbitrary-precision `big.Int` numbers to strings. In all languages, this is the recommended way of passing arbitrary-precision values.

More specifically in Go, what you'd like to do is to provide `MarshalJSON`/`UnmarshalJSON` methods for your record objects. Here's a quick sample that should help you to start:

```go
type Record struct {
	BigInt *big.Int
}

func (r Record) MarshalJSON() ([]byte, error) {
	payload := fmt.Sprintf(`{"big_int":"%s"}`, r.BigInt.String())
	return []byte(payload), nil
}

func (r *Record) UnmarshalJSON(data []byte) error {
	var m map[string]string
	err := json.Unmarshal(data, &m)
	if err != nil {
		return err
	}
	v, ok := m["big_int"]
	if !ok {
		v = "0"
	}
	return json.Unmarshal([]byte(v), &r.BigInt)
}
```

And the associated indexing call:

```go
i := big.NewInt(9223372036854775807)
i = i.Add(i, big.NewInt(1))

res, err := index.SaveObjects([]Record{
	{BigInt: i},
}, opt.AutoGenerateObjectIDIfNotExist(true))
```

**Comment by townsymush** [comment]
Thanks for the response,

I was actually running the code with Go Run when I did the sample, didn't actually realise there were differences when you make the executable (Still fairly new to Go)

Thanks again for your response really helpful
