### ISSUE TITLE
ExhaustionOfTryableHostsErr meaning

### ISSUE THREAD

**Issue by zeroidentidad** [algolia/algoliasearch-client-go#703]
- Algolia Client Version: 2.25.0
- Language Version: Go

### Description

I get "All hosts have been contacted unsuccessfully" from a ExhaustionOfTryableHostsErr constant. I dont know that means or the reason, I have runned succesfully my codebase in previous times without this happens using the correct AppID, ApiKey and index name. I saw https://www.algolia.com/doc/api-client/troubleshooting/faq but I couldn't find an answer

**Comment by zeroidentidad** [comment]
An email to contact support and send the report?
- when using ```curl -sL https://algolia.com/downloads/diag.sh > ./diag.sh && sudo ./diag.sh ApplicationID```

**Comment by samouss** [comment]
Hello! The client has an internal retry strategy, when it cannot reach one server it will automatically try another one i.e. another host. By default every application have 3 hosts. This error means we've tried to contact the three of them and didn't get an answer i.e. no more hosts to contact. It's most likely because: credentials are incorrect or a network issue. If the issue persist please send a message to the support.
